WIP Add support to forward external domains DNS queries to dnsmasq
openstack-k8s-operators/ansible-microshift-role pull request #27
Opened 2023-06-01 08:26 UTC by danpawlik

That feature will be mostly used by the CI for simulating the external domains that exists normaly in the Internet.
For example, if domain '.sftests.com' have many subdomains and not each domain is registered domain in the Openshift cluster and the domain is just for test (not registered in any DNS authority) it will fail name resolution inside the pod with an error:

    "curl: (6) Could not resolve host: test.sftests.com"

In that case, we are adding custom domain inside the codedns configuration configmap, which will forward the DNS queries made for that domain to the dnsmasq, which is installed on the host. The dnsmasq (which is started by NetworkManager) have proper entries to resolve the domain.

2023-06-02 13:39 UTC, TristanCacqueray requested changes

2023-06-02 13:39 UTC, TristanCacqueray commented on defaults/main.yaml
> +#     address: 10.0.0.1
I thought that thanks to dnsmasq, the route should already resolve on the host, so why do we need to define the domain explicitly?

2023-06-02 13:39 UTC, TristanCacqueray commented on tasks/additional_domains.yaml
> +      notify: Restart Openshift DNS
Isn't there a simpler way to update the config map? These tasks looks a bit brittle. Isn't there a kubectl invocation to inject the new Corefile in the cm?

2023-06-02 14:47 UTC, TristanCacqueray commented on templates/corefile.yaml
> +    }
Why not simply:  `forward . {{ ansible_ipv4 }}:53`

2023-06-02 15:07 UTC, danpawlik commented on defaults/main.yaml
> +#     address: 10.0.0.1
that's a good point.
After last debuging, some part of the PS would be changed.
tl;dr by setting dns=dnsmasq in NetworkManager, the nameserver is set to 127.0.0.1 and after restarting the openshuft-dns daemonset, pods are trying to resolve domains by making query to 127.0.0.1. Soon I will do that patch set ready to review!

2023-06-05 08:34 UTC, TristanCacqueray requested changes

2023-06-05 08:34 UTC, TristanCacqueray commented on defaults/main.yaml
> +coredns_config_dir: "/etc/coredns-configs"
Why are we keeping a copy outside of the config map?

2023-06-05 08:34 UTC, TristanCacqueray commented on templates/corefile.yaml
> +.:5353 {
Is this yaml ?

2023-06-05 08:34 UTC, TristanCacqueray commented on tasks/coredns.yaml
> +      notify: Restart Openshift DNS
Is there a reason we are not using the kubectl command to update the config, e.g.:

```
    kubectl create cm dns-default --from-file=./Corefile --dry-run -o yaml | \
      kubectl -n openshift-dns apply -f -
```

2023-06-06 07:22 UTC, danpawlik commented on templates/corefile.yaml
> +.:5353 {
no, it is like json, but withou quotes

2023-06-06 07:24 UTC, danpawlik commented on tasks/coredns.yaml
> +      notify: Restart Openshift DNS
yes, such update is sensitive IMHO and would like to keep all the files that have been created. 
Normally, it can be done simple by using kubectl patch + /usr/local/bin/yq ".data.Corefile = \"$(cat {{ coredns_config_dir }}/corefile.raw)\"", but it looks ugly and was harder to find a bug

2023-06-06 13:48 UTC, danpawlik commented on defaults/main.yaml
> +coredns_config_dir: "/etc/coredns-configs"
IMHO It's better to keep a backup. Also later we are operating on the default config

2023-06-06 13:49 UTC, TristanCacqueray approved these changes
Thanks!

2023-06-06 13:51 UTC, TristanCacqueray commented on templates/corefile.yaml
> +.:5353 {
Ok, then perhaps the file should be named `Corefile.j2`

2023-06-06 13:52 UTC, TristanCacqueray commented on tasks/coredns.yaml
> +      notify: Restart Openshift DNS
I see, that's annoying. Well perhaps we could dump the whole cm, and use the `kubectl create --dry-run | kubectl apply` trick to update the Corefile

2023-06-07 06:16 UTC, merged